<?php 
$BLOG_OWNER_ALREADY_EXISTS = -100; // this is a negative value because blogID values are positive
$POST_CREATED_SUCCESSFULLY = 1;
$POST_CREATION_FAILED = 2;
$POST_EDITED_SUCCESSFULLY = 4;
$POST_EDIT_FAILED = 8;
$POST_DELETED_SUCCESSFULLY = 16;
$POST_DELETE_FAILED = 32;
?>
